### ISSUE TITLE
AC-coverage error

### ISSUE THREAD

**Issue by joakimmoller** [Odin-SMR/odincal-lambda#16]
# 🐛 Description
Some unknown error, while calculation the 15min bins for ac_coverage

# 🔢 To reproduce
input:
``` json
{
  "name": "ac1/342/342e032a.ac1",
  "type": "ac1"
}
```
# ✌🏽 Expected behaviour

Raise/catch expected exceptions for retry or move to known succeed state if this is expected.

# 📷 Screenshots

If applicable

# 💻 Traceback

  | 2023-11-09T08:44:30.614+01:00 | START RequestId: 544bd636-facf-4078-9bf8-1dd9e3d57e2f Version: $LATEST
-- | -- | --
  | 2023-11-09T08:44:30.614+01:00 | [DEBUG] level1b.pre-process.handler: setting up postgres before pre-processing of 342cf799.ac2
  | 2023-11-09T08:44:31.006+01:00 | [DEBUG] level1b.pre-process.handler: checking attitude coverage for 342cf799.ac2
  | 2023-11-09T08:44:31.176+01:00 | 'DataFrame' object has no attribute 'stw_bin': AttributeError
  | 2023-11-09T08:44:31.176+01:00 | Traceback (most recent call last):
  | 2023-11-09T08:44:31.176+01:00 | File "/var/task/odincal_handler.py", line 159, in preprocess_handler
  | 2023-11-09T08:44:31.176+01:00 | assert_acfile_has_data_coverage(ac_file, backend, pg_string)
  | 2023-11-09T08:44:31.176+01:00 | File "/var/task/ac_coverage.py", line 85, in assert_acfile_has_data_coverage
  | 2023-11-09T08:44:31.176+01:00 | start = df.stw_bin.min()
  | 2023-11-09T08:44:31.176+01:00 | File "/var/task/pandas/core/generic.py", line 5067, in __getattr__
  | 2023-11-09T08:44:31.176+01:00 | return object.__getattribute__(self, name)
  | 2023-11-09T08:44:31.176+01:00 | AttributeError: 'DataFrame' object has no attribute 'stw_bin'
  | 2023-11-09T08:44:31.177+01:00 | END RequestId: 544bd636-facf-4078-9bf8-1dd9e3d57e2f
  | 2023-11-09T08:44:31.177+01:00 | REPORT RequestId: 544bd636-facf-4078-9bf8-1dd9e3d57e2f Duration: 563.26 ms Billed Duration: 564 ms Memory Size: 2048 MB Max Memory Used: 219 MB

**Comment by joakimmoller** [comment]
Solved in level0 - pipeline
